### ISSUE TITLE
itk-elastix-opencl lags itk-elastix on pypi

### ISSUE THREAD

**Issue by khahn-hf** [InsightSoftwareConsortium/ITKElastix#202]
Hello,

Noticed `itk-elastix-opencl` is at 0.13.0, but `itk-elastix` is at 0.15.0 on pypi. Is there any specific reason (e.g. is OpenCL unsupported)?

Thanks!

**Comment by ntatsisk** [comment]
Hi @khahn-hf, there are some long-standing issues related to the OpenCL in Elastix: https://github.com/SuperElastix/elastix/issues/226, https://github.com/SuperElastix/elastix/issues/218, https://github.com/SuperElastix/elastix/issues/107, https://github.com/SuperElastix/elastix/issues/70. Since there is some progress being made these days, I think it might better that a new version of `itk-elastix-opencl` waits for these updates first.

**Comment by pypi20200320** [comment]
Hi, All. There are new version of itk-elastix-opencl which can be runed successfullly ? I had tried itk-elastix-opencl 0.11.0 and 0.13.0,  both all can't run succeed. The error info shows below:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/itk/support/lazy.py", line 138, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "/opt/conda/lib/python3.9/site-packages/itk/support/base.py", line 130, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "/opt/conda/lib/python3.9/site-packages/itk/support/base.py", line 289, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/conda/lib/python3.9/site-packages/itk/support/../ElastixPython.py", line 13, in <module>
    from . import _ElastixPython
AttributeError: PyCapsule_Import "_ITKCommonPython._C_API" is not valid

**Comment by completementgaga** [comment]
Hello, all. Any news on itk-elastix-opencl ?

**Comment by thewtex** [comment]
Hi, we have a few other issues to address before this.
