### ISSUE TITLE
itk module appears empty (no attributes)

### ISSUE THREAD

**Issue by williamc96** [InsightSoftwareConsortium/ITKElastix#203]
After updating my itkElastix version today I seem unable to use anything. I tried restarting and using a fresh conda environment as well, but it seems that itk has no attributes and isn't importing anything.  Below is where I installed in the new conda environment and then just showing some example calls. I think I was on 0.15.3 before when everything was working but I'm not 100% certain, and when I try version 0.14.2 I get the same issue... Any thoughts? 
```
(myenv) MacBook-Pro-2:3Dregistration williamcunningham$ pip install itk-elastix
Collecting itk-elastix
  Downloading itk_elastix-0.16.0-cp310-cp310-macosx_11_0_arm64.whl (12.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 10.5 MB/s eta 0:00:00
Collecting itk>=5.3.0
  Downloading itk-5.3.0-cp310-cp310-macosx_11_0_arm64.whl (8.3 kB)
Collecting itk-numerics==5.3.0
  Downloading itk_numerics-5.3.0-cp310-cp310-macosx_11_0_arm64.whl (34.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.6/34.6 MB 10.6 MB/s eta 0:00:00
Collecting itk-io==5.3.0
  Downloading itk_io-5.3.0-cp310-cp310-macosx_11_0_arm64.whl (18.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 8.9 MB/s eta 0:00:00
Collecting itk-segmentation==5.3.0
  Downloading itk_segmentation-5.3.0-cp310-cp310-macosx_11_0_arm64.whl (12.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 9.8 MB/s eta 0:00:00
Collecting itk-filtering==5.3.0
  Downloading itk_filtering-5.3.0-cp310-cp310-macosx_11_0_arm64.whl (47.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 MB 5.4 MB/s eta 0:00:00
Collecting itk-core==5.3.0
  Downloading itk_core-5.3.0-cp310-cp310-macosx_11_0_arm64.whl (57.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 MB 6.4 MB/s eta 0:00:00
Collecting itk-registration==5.3.0
  Downloading itk_registration-5.3.0-cp310-cp310-macosx_11_0_arm64.whl (18.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 5.3 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.24.2-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 5.7 MB/s eta 0:00:00
Installing collected packages: numpy, itk-core, itk-numerics, itk-io, itk-filtering, itk-segmentation, itk-registration, itk, itk-elastix
Successfully installed itk-5.3.0 itk-core-5.3.0 itk-elastix-0.16.0 itk-filtering-5.3.0 itk-io-5.3.0 itk-numerics-5.3.0 itk-registration-5.3.0 itk-segmentation-5.3.0 numpy-1.24.2



(myenv) MacBook-Pro-2:3Dregistration williamcunningham$ python
Python 3.10.9 (main, Mar  8 2023, 04:44:30) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import itk
>>> itk.__ (showing autocomplete options, tab on itk. adds the __ then shows the below)
itk.__annotations__     itk.__doc__             itk.__getattribute__(   itk.__le__(             itk.__new__(            itk.__repr__()          itk.__subclasshook__(
itk.__class__(          itk.__eq__(             itk.__gt__(             itk.__loader__          itk.__package__         itk.__setattr__(        
itk.__delattr__(        itk.__file__            itk.__hash__()          itk.__lt__(             itk.__path__            itk.__sizeof__()        
itk.__dict__            itk.__format__(         itk.__init__(           itk.__name__            itk.__reduce__()        itk.__spec__            
itk.__dir__(            itk.__ge__(             itk.__init_subclass__(  itk.__ne__(             itk.__reduce_ex__(      itk.__str__()           
>>> itk.imread
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'itk' has no attribute 'imread'
>>> itk.imread()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'itk' has no attribute 'imread'
>>> parameterObj = itk.ParameterObject.New()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'itk' has no attribute 'ParameterObject'
```

**Comment by williamc96** [comment]
I think this is because the ARM wheels aren't set up for 0.16.0 maybe??
[This](https://github.com/InsightSoftwareConsortium/ITKElastix/pull/190/commits/c115d94a82a408b57ba3a5ae9bb4348cbfc0c115) fixed it for 0.15.1 I think, but not for later versions. 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/89996611/224814280-bbe14374-f60d-4722-91eb-b19a54d897c2.png">

The [file](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/4742884b1c3a4899b3bcd7c93813381915ba91bf/setup.py) also still says 0.15.1 but not sure since I've never done development for python packages.

**Comment by williamc96** [comment]
I didn't mean to close it..

**Comment by williamc96** [comment]
(Accidentally closed it)

**Comment by m-albert** [comment]
I'm also experiencing this problem on mac (M2), where the `lib/python3.11/site-packages/itk/__init__.py` file is empty.

On linux it seems to work fine.

**Comment by williamc96** [comment]
FYI @m-albert you can use an older version (pip install --force-reinstall -v "itk-elastix==0.14.2"). This was fixed for m1 macs

**Comment by williamc96** [comment]
FYI @m-albert you can fix this with an older version (pip install --force-reinstall -v "itk-elastix==0.14.2"). This was fixed in [this thread](https://github.com/InsightSoftwareConsortium/ITKElastix/issues/136).

**Comment by m-albert** [comment]
Thanks @williamc96, will try it out!
